const $=id=>document.getElementById(id);
const FALLBACK_MARKETS=[
 {symbol:"BTC",priceDisplay:"—",change:null,source:"Global feed"},
 {symbol:"GOLD",priceDisplay:"—",change:null,source:"Global feed"},
 {symbol:"BRENT",priceDisplay:"—",change:null,source:"Global feed"},
 {symbol:"S&P500",priceDisplay:"—",change:null,source:"Global feed"},
 {symbol:"NASDAQ",priceDisplay:"—",change:null,source:"Global feed"},
 {symbol:"DXY",priceDisplay:"—",change:null,source:"Global feed"}
];
let map,eqLayer,naturalLayers={},intelLayer,liveEvents=[],marketData=[...FALLBACK_MARKETS],marketMoveValue=0;
let filter="all",feedFilter="all";

const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function fmtTime(ts){return new Date(ts).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})}
function ageText(ts){const m=Math.max(0,Math.round((Date.now()-ts)/60000));return m<60?`${m}m`:m<1440?`${Math.round(m/60)}h`:`${Math.round(m/1440)}d`}
function regionOf(e){if(e.region&&e.region!=="GLOBAL")return e.region;return e.region||"GLOBAL"}
function markerIcon(cls,size=10){return L.divIcon({className:"",html:`<div class="event-dot ${cls}"></div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]})}
function initMap(){if(map)return;map=L.map("map",{zoomControl:true,minZoom:2,worldCopyJump:true}).setView([24,15],2);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);eqLayer=L.layerGroup().addTo(map);["wildfire","storm","volcano","natural"].forEach(k=>naturalLayers[k]=L.layerGroup().addTo(map));intelLayer=L.layerGroup().addTo(map)}
function impactForEvent(e){const t=((e.type||"")+" "+(e.title||"")+" "+(e.tags||[]).join(" ")).toLowerCase();let o={OIL:0,GOLD:0,BTC:0,NASDAQ:0,DXY:0,"S&P500":0};const add=(k,v)=>o[k]=Math.max(-10,Math.min(10,(o[k]||0)+v));if(/war|conflict|missile|attack|military|sanction|ceasefire|geopolit/.test(t)){add("GOLD",4);add("OIL",3);add("BTC",-2);add("NASDAQ",-2);add("S&P500",-2);add("DXY",2)}if(/oil|gas|pipeline|tanker|shipping|strait|energy|opec|refiner/.test(t)){add("OIL",5);add("GOLD",1);add("NASDAQ",-1)}if(/inflation|cpi|rates|interest|central bank|fed|ecb|jobs|gdp|tariff|trade/.test(t)){add("DXY",3);add("GOLD",2);add("NASDAQ",-2);add("S&P500",-2);add("BTC",-1)}if(/earthquake/.test(t))add("GOLD",1);const mult=Math.max(.5,Math.min(1.5,(Number(e.severity)||5)/7));Object.keys(o).forEach(k=>o[k]=Math.round(Math.max(-10,Math.min(10,o[k]*mult))));return o}
function scoreClass(v){return v>0?"up":v<0?"down":"flat"}function renderImpact(e){const imp=impactForEvent(e),nonzero=Object.entries(imp).filter(([,v])=>v!==0);$("mr").textContent=`${String(e.type||"intel").toUpperCase()} · ${e.source||"SOURCE"}`;$("mt").textContent=e.title;$("md").textContent=e.description||"Observed source event.";$("mi").innerHTML=(nonzero.length?nonzero:Object.entries(imp)).map(([k,v])=>`<div><span>${k}</span><b class="${scoreClass(v)}">${v>0?"+":""}${v}</b></div>`).join("");const sl=$("sourceLink");if(sl){if(e.url){sl.href=e.url;sl.classList.remove("hide")}else sl.classList.add("hide")}$("modal").classList.remove("hide")}
async function loadEarthquakes(){const r=await fetch("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson",{cache:"no-store"});if(!r.ok)throw Error("USGS "+r.status);const j=await r.json(),events=[];eqLayer.clearLayers();j.features.slice(0,120).forEach(f=>{const[lon,lat]=f.geometry.coordinates,mag=Number(f.properties.mag||0);events.push({id:"eq-"+f.id,type:"earthquake",category:"natural",source:"USGS",title:`M${mag.toFixed(1)} · ${f.properties.place||"Earthquake"}`,description:"USGS real-time earthquake feed",lat,lon,time:f.properties.time,severity:Math.min(10,Math.max(2,Math.round(mag*1.4)))})});$("eqCount").textContent=events.length;return events}
async function loadEonet(){return[]}
async function loadIntel(){const urls=[{name:"LOCAL",url:`data/intel.json?t=${Date.now()}`},{name:"RAW",url:`https://raw.githubusercontent.com/alperen15100/ecrintel/main/data/intel.json?t=${Date.now()}`}],payloads=[];for(const s of urls){try{const r=await fetch(s.url,{cache:"no-store"});if(!r.ok)throw Error(r.status);const j=await r.json();if(Array.isArray(j.events))payloads.push({name:s.name,j,count:j.events.length})}catch(e){console.warn("intel source failed",s.name,e)}}if(!payloads.length)return[];payloads.sort((a,b)=>b.count-a.count);const j=payloads[0].j,arr=j.events.map((x,i)=>({...x,id:String(x.id||`intel-${i}`),time:Number.isFinite(typeof x.time==='number'?x.time:Date.parse(x.time))?(typeof x.time==='number'?x.time:Date.parse(x.time)):Date.now(),severity:Number(x.severity)||5}));$("intelCount").textContent=arr.length;return arr}
async function loadMarkets(){let data=[...FALLBACK_MARKETS];try{const r=await fetch(`data/markets.json?t=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(Array.isArray(j.markets)&&j.markets.length)data=j.markets}catch(e){console.warn(e)}marketData=data;renderMarkets()}
function renderMarkets(){const root=$("markets");if(root)root.innerHTML=marketData.map(x=>{const c=x.change,cls=c==null?"flat":c>=0?"up":"down",ch=c==null?"—":`${c>=0?"+":""}${Number(c).toFixed(2)}%`;return `<div class="market"><span>${esc(x.symbol)}<small> ${esc(x.source||"Global feed")}</small></span><b>${esc(x.priceDisplay||x.price||"—")}</b><i class="${cls}">${ch}</i></div>`}).join("")}
function matchesFeed(e){return feedFilter==="all"?true:feedFilter==="natural"?e.category==="natural":e.category===feedFilter}function renderFeed(){const root=$("feed");if(!root)return;root.innerHTML=liveEvents.filter(matchesFeed).sort((a,b)=>b.time-a.time).slice(0,40).map(e=>`<div class="feeditem" data-event="${esc(e.id)}"><time>${ageText(e.time)}</time><em>${esc(String(e.category||e.type||'intel').toUpperCase())} · ${esc(e.source||'Source')}</em><b>${esc(e.title)}</b><p>${esc(e.description||'')}</p></div>`).join("")}
function dedupeEvents(arr){const seen=new Set();return arr.filter(e=>{const k=String(e.url||e.id||e.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
function updateActivity(){}function updateImpactEngine(){}function setLayerVisibility(){}function refreshSuite(){}function checkWatchAlerts(){}function setupWhy(){}function setupAssetIntel(){}function renderWatch(){}function setupSearch(){}function loadCalendar(){}function enableAlerts(){}
async function refreshData(){const[eq,nat,intel]=await Promise.all([loadEarthquakes().catch(()=>[]),loadEonet().catch(()=>[]),loadIntel().catch(()=>[])]);liveEvents=dedupeEvents([...eq,...nat,...intel]);await loadMarkets();renderFeed();window.dispatchEvent(new CustomEvent('ecrintel:data',{detail:{events:liveEvents.length,markets:marketData.length,at:Date.now()}}));const lu=$("lastUpdate");if(lu)lu.textContent=fmtTime(Date.now())}
const ASSETS=["BTC","ETH","GOLD","BRENT","WTI","S&P500","NASDAQ","DXY","EUR/USD","NIKKEI","DAX","FTSE","HANG SENG"];
function setup(){initMap();document.querySelectorAll("#intelTabs button").forEach(b=>b.onclick=()=>{feedFilter=b.dataset.feed;renderFeed()});const x=$("x");if(x)x.onclick=()=>$("modal").classList.add("hide");refreshData().catch(console.warn);setInterval(()=>refreshData().catch(console.warn),5*60*1000)}document.addEventListener("DOMContentLoaded",setup);