const $=id=>document.getElementById(id);
const FALLBACK_MARKETS=[{symbol:"BTC",priceDisplay:"—",change:null,source:"Global feed"},{symbol:"GOLD",priceDisplay:"—",change:null,source:"Global feed"},{symbol:"BRENT",priceDisplay:"—",change:null,source:"Global feed"},{symbol:"S&P500",priceDisplay:"—",change:null,source:"Global feed"},{symbol:"NASDAQ",priceDisplay:"—",change:null,source:"Global feed"},{symbol:"DXY",priceDisplay:"—",change:null,source:"Global feed"}];
let map,eqLayer,naturalLayers={},intelLayer,liveEvents=[],marketData=[...FALLBACK_MARKETS],marketMoveValue=0;let filter="all",feedFilter="all";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function fmtTime(ts){return new Date(ts).toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})}function ageText(ts){const m=Math.max(0,Math.round((Date.now()-ts)/60000));return m<60?`${m}m`:m<1440?`${Math.round(m/60)}h`:`${Math.round(m/1440)}d`}
function regionOf(e){if(e.region&&e.region!=="GLOBAL")return e.region;return e.region||"GLOBAL"}
function impactForEvent(e){const t=((e.type||"")+" "+(e.title||"")+" "+(e.tags||[]).join(" ")).toLowerCase();let o={OIL:0,GOLD:0,BTC:0,NASDAQ:0,DXY:0,"S&P500":0};const add=(k,v)=>o[k]=Math.max(-10,Math.min(10,(o[k]||0)+v));if(/war|conflict|missile|attack|military|sanction|ceasefire|geopolit/.test(t)){add("GOLD",4);add("OIL",3);add("BTC",-2);add("NASDAQ",-2);add("S&P500",-2);add("DXY",2)}if(/oil|gas|pipeline|tanker|shipping|strait|energy|opec|refiner/.test(t)){add("OIL",5);add("GOLD",1);add("NASDAQ",-1)}if(/inflation|cpi|rates|interest|central bank|fed|ecb|jobs|gdp|tariff|trade/.test(t)){add("DXY",3);add("GOLD",2);add("NASDAQ",-2);add("S&P500",-2);add("BTC",-1)}const mult=Math.max(.5,Math.min(1.5,(Number(e.severity)||5)/7));Object.keys(o).forEach(k=>o[k]=Math.round(Math.max(-10,Math.min(10,o[k]*mult))));return o}
function initMap(){/* mobile product intentionally has no map */}
async function loadEarthquakes(){return[]}async function loadEonet(){return[]}
async function loadIntel(){const urls=[{name:"LOCAL",url:`data/intel.json?t=${Date.now()}`},{name:"RAW",url:`https://raw.githubusercontent.com/alperen15100/ecrintel/main/data/intel.json?t=${Date.now()}`}],payloads=[];for(const s of urls){try{const r=await fetch(s.url,{cache:"no-store"});if(!r.ok)throw Error(r.status);const j=await r.json();if(Array.isArray(j.events))payloads.push({name:s.name,j,count:j.events.length})}catch(e){console.warn("intel",s.name,e)}}if(!payloads.length)return[];payloads.sort((a,b)=>(b.count-a.count)||((Date.parse(b.j.updatedAt)||0)-(Date.parse(a.j.updatedAt)||0)));const j=payloads[0].j;return j.events.map((x,i)=>({...x,id:String(x.id||`intel-${i}`),time:Number.isFinite(typeof x.time==='number'?x.time:Date.parse(x.time))?(typeof x.time==='number'?x.time:Date.parse(x.time)):Date.now(),severity:Number(x.severity)||5}))}
async function loadMarkets(){let data=[...FALLBACK_MARKETS];try{const r=await fetch(`data/markets.json?t=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(Array.isArray(j.markets)&&j.markets.length)data=j.markets}catch(e){console.warn(e)}marketData=data;const moves=data.filter(x=>Number.isFinite(x.change)).map(x=>Math.abs(x.change));marketMoveValue=moves.length?moves.reduce((a,b)=>a+b,0)/moves.length:0;renderMarkets()}
function renderMarkets(){const root=$("markets");if(root)root.innerHTML=marketData.map(x=>{const c=x.change,cls=c==null?"flat":c>=0?"up":"down",ch=c==null?"—":`${c>=0?"+":""}${c.toFixed(2)}%`;return `<div class="market"><span>${esc(x.symbol)}<small> ${esc(x.source||"Global feed")}</small></span><b>${esc(x.priceDisplay||x.price||"—")}</b><i class="${cls}">${ch}</i></div>`}).join("");const tick=$("ticker");if(tick)tick.innerHTML=marketData.slice(0,6).map(x=>`<span><b>${esc(x.symbol)}</b> ${esc(x.priceDisplay||x.price||"—")}</span>`).join("")}
function matchesFeed(e){if(feedFilter==="all")return true;if(feedFilter==="natural")return e.category==="natural";return e.category===feedFilter}
function renderFeed(){const root=$("feed");if(!root)return;const arr=liveEvents.filter(matchesFeed).sort((a,b)=>(b.time-a.time)||(b.severity-a.severity)).slice(0,40);root.innerHTML=arr.length?arr.map(e=>`<div class="feeditem" data-event="${esc(e.id)}"><time>${ageText(e.time)}</time><em>${esc(String(e.category||e.type||'intel').toUpperCase())} · ${esc(e.source||'Source')}</em><b>${esc(e.title)}</b><p>${esc(e.description||regionOf(e)||'')}</p></div>`).join(""):`<div class="feeditem"><p>No current intelligence.</p></div>`}
function dedupeEvents(arr){const seen=new Set();return arr.filter(e=>{const k=String(e.url||e.id||e.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
async function refreshData(){const intel=await loadIntel().catch(()=>[]);if(intel.length)liveEvents=dedupeEvents(intel);await loadMarkets();renderFeed();window.dispatchEvent(new CustomEvent('ecrintel:data',{detail:{events:liveEvents.length,markets:marketData.length,at:Date.now()}}))}
const ASSETS=["BTC","ETH","GOLD","BRENT","WTI","S&P500","NASDAQ","DXY","EUR/USD","NIKKEI","DAX","FTSE","HANG SENG"];
function setup(){document.querySelectorAll("#intelTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#intelTabs button").forEach(x=>x.classList.remove("on"));b.classList.add("on");feedFilter=b.dataset.feed;renderFeed()});refreshData().catch(console.warn);setInterval(()=>{if(!document.hidden)refreshData().catch(console.warn)},60*1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshData().catch(console.warn)});window.addEventListener('online',()=>refreshData().catch(console.warn))}
document.addEventListener("DOMContentLoaded",setup);